import { Ticket, Technician, UserProfile } from './types';

export const CURRENT_USER: UserProfile = {
  id: 'usr-001',
  name: 'สมชาย ศรีสุวรรณ',
  email: 'somchai.s@univ.ac.th',
  role: 'admin',
  roleLabel: 'เจ้าหน้าที่ไอที / แอดมินระบบ',
  department: 'ศูนย์เทคโนโลยีสารสนเทศและบริการเครือข่าย',
  phone: '081-889-4512',
  avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBnWTsL_F2iP2oickxsBBUrQu5xTSfx2c1ubl5wm7wjXarPHiWrFJITGxiQJatzdfhybnmHFLyCoMwxIXxAhyMoxV59crpYJ3PpLl9_NDgB-WTK7xj7YTxoc7EW9ZcZLXveb3cuYFc_J-vgMMtrBoOSQ2MAhXm6JfJKtx3pn0lOvIXq3pt8GIRgknFMFZvDj2oH9xdv-H_eLPBIVotoHN8PkQiQY_x6cGPeE4YUxmsLjUHd8hL9VR0',
  campus: 'วิทยาเขตหลัก (Main Campus)',
};

export const TECHNICIANS_LIST: Technician[] = [
  {
    id: 'tech-01',
    code: 'IT-04',
    name: 'วรวิทย์ ยิ่งยง',
    role: 'ช่างฮาร์ดแวร์ & โสตฯ',
    department: 'ฝ่ายบริการอุปกรณ์คอมพิวเตอร์',
    location: 'หน้างาน: อาคารเรียนรวม',
    status: 'available',
    activeLoad: 2,
    avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAfP2hFoqefB-ZXmay836sp_LlaLisj-lQcqAgBxFCIbZGWUaVN06HRgYAEhCBdZHBGiiXairDtSQhEiEFhsIJ0Eslqdy3jmP9FldoJbEyGWUV7U2o7dyY-V7BdignbAHcLn3ZvFte-ShZKDBS4ltDnF1K53JHvpYUMTD7_lC88u3iovlrORGf5Bqlc6-7Hbghetn3t0KMaOVa4MZp22oB6peu1ANtjQeUhiG6_WxiWRlFwN9IvrXI',
    extension: '4401',
    phone: '084-219-4401',
  },
  {
    id: 'tech-02',
    code: 'IT-06',
    name: 'กานดา นวลสว่าง',
    role: 'วิศวกรระบบเครือข่าย',
    department: 'ฝ่ายระบบเครือข่ายและความปลอดภัย',
    location: 'ศูนย์คอมพิวเตอร์ อาคาร 3',
    status: 'available',
    activeLoad: 0,
    avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAFB3Q2fOssupJ0qcvL__-Tu5gs5hO7k5jjuPWX0iaSZZ7lBVOzwLbMV-gp0Nqpgonu_V2vAMDwDMEO0lvqPF1zbfvtkbnc8DmxRl0na6Zay5-jMQFHmsth5FnGQDEv126FqrEgWst9EEXyedudkstLR1ykISScgLWCbsosxTLoMRcjZnuKhkUoyUQtGcIz0EMPkWcvN7RaoHnau6FK6WUDh2Ozu2wDgF05UW2DFQJu10Frr8Bro9U',
    extension: '4405',
    phone: '089-771-4405',
  },
  {
    id: 'tech-03',
    code: 'IT-02',
    name: 'ธนกร ภัทรเดช',
    role: 'บริการซอฟต์แวร์และแอป',
    department: 'ฝ่ายบริการแอปพลิเคชันและพัฒนาระบบ',
    location: 'กำลัง Remote ช่วยผู้ใช้',
    status: 'busy',
    activeLoad: 3,
    avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBxqIBX1Ai2kASVAhVrvt2vcmjkiKFW7JcCxvIvHiIOi5Zhzib5ZDA2ZdJulA8oUdoTDIV9ehKEYdQvCZBVA44389rZnP36Oetlb3D8OL6YDgQwBJoARVku744i1Gm4GruiXKnzn3aArCtQABlimQ08eGucDRMWSn9AMi44It0AAYqCK3APM3qZD6E6vf56NK7RAaTwUyx8yqKtgovN-TppAthd-fEoWdg20HRgXCFGfDidffT4KhI',
    extension: '4403',
    phone: '081-334-4403',
  },
  {
    id: 'tech-04',
    code: 'IT-08',
    name: 'ณัฐพล สดใส',
    role: 'ช่างเทคนิคโครงข่าย',
    department: 'ฝ่ายโครงสร้างพื้นฐานระบบ',
    location: 'พร้อมออกปฏิบัติการ',
    status: 'available',
    activeLoad: 1,
    avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCRx8sBBcPz8sybMlgMQl_qXmLMkO991RJsPgfySKZZxUGzhe0TXh_0gB3GcWSGH9fKezyPY1x4Sdpgf-f-TtsWep1cupW2EZtg9tuaGZH6ym3Tbj8DLaamn0e4GY0WCcl72IZid26YLtEYtys1w92ZMhBwuL2HzGBacaqMWgIzrvwluZ5aC4zQyDzPdxh4xgIUNr7ddIJEeN7hRntrPErTXtBa9wsunNQbvjABe-fOnHVlzax6vZY',
    extension: '4408',
    phone: '086-455-4408',
  },
];

// Initial tickets are empty so user starts with clean real data
export const INITIAL_TICKETS: Ticket[] = [];

export const SAMPLE_TICKETS_TEMPLATE: Ticket[] = [
  {
    id: 'TK-2024-0042',
    title: 'เปิดเครื่องคอมพิวเตอร์แล้วขึ้นจอฟ้า (Blue Screen of Death) รหัสข้อผิดพลาด CRITICAL_PROCESS_DIED',
    description: 'ขณะกำลังใช้งานโปรแกรม SAP เพื่อปิดงบประจำเดือน อยู่ดีๆ เครื่องดับไปเองกะทันหัน จากนั้นตัวเครื่องพยายามรีสตาร์ทแล้วขึ้นหน้าจอสีฟ้า (Blue Screen) แสดงรหัสข้อผิดพลาดว่า CRITICAL_PROCESS_DIED ทางผู้แจ้งได้ลองปิดสวิตช์แล้วเปิดเครื่องใหม่จำนวน 3 รอบ แต่ยังค้างที่จอฟ้าแบบเดิม ไม่สามารถเข้าสู่ระบบปฏิบัติการ Windows ได้เลย จำเป็นต้องใช้ไฟล์เอกสารด่วนเพื่อส่งต่อผู้บริหารในช่วงบ่ายนี้ค่ะ',
    category: 'Computer',
    priority: 'High',
    status: 'In Progress',
    requesterName: 'คุณกัญญา วัฒนากุล',
    requesterPhone: '089-452-9912',
    requesterEmail: 'kanya.w@org.ac.th',
    requesterDept: 'แผนกบัญชีและการเงิน',
    requesterTitle: 'เจ้าหน้าที่การเงินชำนาญการ',
    requesterAvatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDiJQsCwr1VqyJmlbGqb8jbSLyYbEle1fwdDCyk1HawtrgmprFZP0-AVsCqR_0ovHtWx7buZKrA280iqm01bYMZJ-BwtG1f1hRofUn7QxXZ1k0gbAooMBzHP-_kkx0Vvg2V3UvjkyMTVXyySjNWftjwl3kAJz7CPCEypnDPu-UL5z-Zpw208VSAFeJnho1oxV3FmYYMbPNHjBXltJqfSjxy16g_5dZmrxP-G7FeAeAVyuDv_z54GZk',
    location: 'อาคาร 3 ชั้น 4 ห้องบัญชี',
    roomDetails: 'โต๊ะทำงานหมายเลข 402',
    assetTag: 'PC-ACC-2022-019',
    assetDevice: 'Dell OptiPlex 7080 MT',
    impact: 'หยุดชะงัก (Critical Duty) มีส่งงบการเงินบ่ายวันนี้',
    createdAt: '24 พ.ค. 2024 • 09:30 น.',
    createdAtRelative: 'เมื่อ 2 ชม. ที่แล้ว',
    slaTargetHours: 4,
    slaRemainingText: 'SLA เป้าหมาย: 4 ชม. (เหลือ 2 ชม. 45 นาที)',
    assignedTech: 'นายณัฐวุฒิ สมบูรณ์',
    assignedTechTitle: 'Senior IT Support (ฝ่ายโครงสร้างพื้นฐานและฮาร์ดแวร์)',
    assignedTechAvatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDVPhObfMsx7YEDOJ2v88dszW25XzPpCdMui0xtmUyskaVG8Shjm0tc0eo_tdc7HkHOAfEuKqGmxdTSiHSlgk4KsGcv_Nshr0Up6Lib-o58Mwpv4v_NIoyAekWeWjWPQpAvzc_RlC6SUrrejGoI4q9pHnQnJaUUuSgpbc-7aahMsB4ROZOPb6HBTQqf_f-ONO2uQK9a2hb4nd0OHobqBpYhcGXd7oTkzgXi9OF4tzreTqvxamUz1BI',
    assignedTechExt: 'ต่อ 4402',
    assignedTechPhone: '02-613-4402',
    spareEquipmentNote: 'เครื่องสำรอง: Dell Vostro #SPARE-04 | สถานะฮาร์ดดิสก์เดิม: อยู่ระหว่างตรวจเช็ก SSD NVMe',
    attachments: [
      {
        name: 'error-bsod.png',
        size: '1.8 MB',
        time: 'แนบเมื่อ 09:30 น.',
        url: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDfIlE9RdNs0Q92s1kO9XLp1JvOyYxdaJE6QC_7fYGIghLIo85sqQRWGk_gZaf2UipxG7cZ8TYFvyJkquDeFv0BlpEmt4Nb46NXAuIZjjBcHFT2IClICqaqkLNvgsot4Ocg6_MY-QUQPgOcJyQDCd_HaJoXnE7-kxFMaWtbXUpyEfzhE7MG8v87Y0fsFqKPS32FKydde0oI4x0edeUgUXeq6T5g0rvLkuAgDr0x_Zc6lihQM-pwOYE',
        previewUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBWe-VsvbsKKi_HYl2tgaxe05o39I9TePwi3X9QScZUUSFFN1M6aOVxaNe0_TMvXtcrqQxXrs7avE4XQD-sONxfoEYepX3PSseCGCyWuHPWOsbBgsXYLz4ONkr5Tudkva8NqxzEsGSNAwgfsu3AWBcEKbQOMvqI2YMPk7HU6FPCl-lDiTH-LFer_SXUqk8hcuK9GpBQeTVZ0TwHQcJoXw8qa_0SHG_J0ktrtkQvSDYM9Tbdph2-TVg',
      },
    ],
    timeline: [
      {
        id: 't1',
        title: 'คุณกัญญา วัฒนากุล แจ้งปัญหาเข้าระบบ',
        time: '24 พ.ค. 2024 • 09:30 น.',
        desc: 'สร้างใบงาน #TK-2024-0042 ผ่านระบบออนไลน์ หมวดหมู่ Computer / Hardware',
        statusText: 'สถานะ: รอรับเรื่อง (Pending)',
        icon: 'flag',
        completed: true,
      },
      {
        id: 't2',
        title: 'นายณัฐวุฒิ สมบูรณ์ รับงานเข้าระบบ',
        time: '24 พ.ค. 2024 • 09:45 น.',
        desc: 'เจ้าหน้าที่ IT แผนกฮาร์ดแวร์กดรับเรื่องและมอบหมายให้ตนเองเป็นผู้รับผิดชอบหลัก',
        statusText: 'สถานะ: รับเรื่องแล้ว (Accepted)',
        icon: 'assignment_turned_in',
        completed: true,
      },
      {
        id: 't3',
        title: 'นายณัฐวุฒิ เริ่มตรวจสอบและนำเครื่องสำรองไปสลับ',
        time: '24 พ.ค. 2024 • 10:15 น.',
        desc: 'นำเครื่องสำรองสำนักงาน (Dell Vostro รหัส SPARE-04) ขึ้นไปติดตั้งที่ห้องบัญชีโต๊ะ 402 เพื่อให้สามารถทำงานต่อเนื่องได้ระหว่างกู้คืนระบบ',
        statusText: 'สถานะปัจจุบัน: กำลังดำเนินการ (In Progress)',
        icon: 'build',
        completed: true,
        isCurrent: true,
      },
      {
        id: 't4',
        title: 'จุดต่อไป: การแก้ไขเสร็จสิ้น (Resolved)',
        time: 'รอการดำเนินการ',
        desc: 'ทดสอบกู้คืนไฟล์บัญชีบน Desktop และเปลี่ยนไดรฟ์ SSD สำเร็จ',
        statusText: 'รอผลการทดสอบระบบ',
        icon: 'check_circle',
        completed: false,
      },
      {
        id: 't5',
        title: 'ปิดงานสมบูรณ์ (Closed)',
        time: 'รอผู้แจ้งประเมินความพึงพอใจ',
        desc: 'ส่งมอบเครื่องจริงกลับคืนและปิดเคสในระบบ',
        statusText: 'รอประเมิน CSAT',
        icon: 'task_alt',
        completed: false,
      },
    ],
    comments: [
      {
        id: 'c1',
        senderName: 'คุณกัญญา วัฒนากุล (ผู้แจ้ง)',
        senderRole: 'ผู้แจ้งปัญหา',
        time: '09:32 น.',
        text: 'เปิดเครื่องแล้วขึ้นหน้าจอสีฟ้าค่ะ รีสตาร์ทดูก็ยังไม่หาย',
        isTech: false,
        avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDiJQsCwr1VqyJmlbGqb8jbSLyYbEle1fwdDCyk1HawtrgmprFZP0-AVsCqR_0ovHtWx7buZKrA280iqm01bYMZJ-BwtG1f1hRofUn7QxXZ1k0gbAooMBzHP-_kkx0Vvg2V3UvjkyMTVXyySjNWftjwl3kAJz7CPCEypnDPu-UL5z-Zpw208VSAFeJnho1oxV3FmYYMbPNHjBXltJqfSjxy16g_5dZmrxP-G7FeAeAVyuDv_z54GZk',
      },
      {
        id: 'c2',
        senderName: 'นายณัฐวุฒิ สมบูรณ์ (ช่างรับผิดชอบ)',
        senderRole: 'IT Support',
        time: '09:48 น.',
        text: 'รับทราบครับ เดี๋ยวผมตรวจสอบให้ครับ กำลังเตรียมเครื่องสำรองขึ้นไปให้สลับทำงานก่อนนะครับ',
        isTech: true,
        avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDVPhObfMsx7YEDOJ2v88dszW25XzPpCdMui0xtmUyskaVG8Shjm0tc0eo_tdc7HkHOAfEuKqGmxdTSiHSlgk4KsGcv_Nshr0Up6Lib-o58Mwpv4v_NIoyAekWeWjWPQpAvzc_RlC6SUrrejGoI4q9pHnQnJaUUuSgpbc-7aahMsB4ROZOPb6HBTQqf_f-ONO2uQK9a2hb4nd0OHobqBpYhcGXd7oTkzgXi9OF4tzreTqvxamUz1BI',
      },
      {
        id: 'c3',
        senderName: 'คุณกัญญา วัฒนากุล (ผู้แจ้ง)',
        senderRole: 'ผู้แจ้งปัญหา',
        time: '09:55 น.',
        text: 'ขอบคุณมากค่ะ มีไฟล์งานสำคัญอยู่ที่ Desktop รบกวนช่วยกู้คืนด้วยนะคะ',
        isTech: false,
        avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDiJQsCwr1VqyJmlbGqb8jbSLyYbEle1fwdDCyk1HawtrgmprFZP0-AVsCqR_0ovHtWx7buZKrA280iqm01bYMZJ-BwtG1f1hRofUn7QxXZ1k0gbAooMBzHP-_kkx0Vvg2V3UvjkyMTVXyySjNWftjwl3kAJz7CPCEypnDPu-UL5z-Zpw208VSAFeJnho1oxV3FmYYMbPNHjBXltJqfSjxy16g_5dZmrxP-G7FeAeAVyuDv_z54GZk',
      },
    ],
  },
  {
    id: 'TK-2024-0891',
    title: 'อินเทอร์เน็ตหลุดทั้งชั้น 4 ห้องเซิร์ฟเวอร์สำรองมีสัญญาณเตือน',
    description: 'สัญญาณอินเทอร์เน็ตหลุดทั้งชั้น 4 คณะวิทยาศาสตร์ สวิตช์หลักในตู้แร็คห้อง 402 มีไฟสีแดงกระพริบเตือน',
    category: 'Network',
    priority: 'Critical',
    status: 'Pending',
    requesterName: 'ดร.ศิริพร บุญเสริม',
    requesterPhone: '089-551-9912',
    requesterEmail: 'siriporn.b@univ.ac.th',
    requesterDept: 'คณะวิทยาศาสตร์ / ภาควิชาวิทยาการคอมพิวเตอร์',
    location: 'อาคารนวัตกรรมดิจิทัล 402',
    roomDetails: 'ห้องปฏิบัติการวิจัย ชั้น 4',
    assetTag: 'SW-CORE-04',
    assetDevice: 'Cisco Catalyst 3850',
    impact: 'กระทบห้องแล็บวิจัยทั้งชั้น 4',
    createdAt: '24 ต.ค. 2024 • 08:50 น.',
    createdAtRelative: 'เมื่อ 14 นาทีที่แล้ว',
    attachments: [],
    timeline: [],
    comments: [],
  },
  {
    id: 'TK-2024-0888',
    title: 'ห้องเรียนรวม 800 ที่นั่ง โปรเจกเตอร์หลักไม่แสดงผลขณะกำลังสอน',
    description: 'โปรเจกเตอร์ตัวหลักขึ้น No Signal สาย HDMI ต่อจากโพเดียมภาพไม่ขึ้น อาจารย์กำลังรอสอนวิชาพื้นฐาน',
    category: 'Computer',
    priority: 'Critical',
    status: 'In Progress',
    requesterName: 'อ.ธีรยุทธ ชัยชนะ',
    requesterPhone: '081-332-9994',
    requesterEmail: 'theerayuth.c@univ.ac.th',
    requesterDept: 'คณะวิศวกรรมศาสตร์',
    location: 'อาคารเรียนรวม 2 ห้อง 201',
    roomDetails: 'ห้องบรรยายรวม 800 ที่นั่ง',
    assetTag: 'PJ-LEC-201',
    assetDevice: 'Panasonic Laser Projector 10,000 lm',
    impact: 'นักศึกษา 800 คนรอการบรรยาย',
    createdAt: '24 ต.ค. 2024 • 08:30 น.',
    createdAtRelative: 'เมื่อ 35 นาทีที่แล้ว',
    assignedTech: 'วรวิทย์ ยิ่งยง',
    attachments: [],
    timeline: [],
    comments: [],
  },
  {
    id: 'TK-2024-0879',
    title: 'เครื่องพิมพ์เอกสารการเงินพิมพ์ไม่ออก ขึ้น Error 50.4 Fuser',
    description: 'เครื่องพิมพ์เลเซอร์สำหรับออกเช็คพิมพ์ติดขัด หน้าจอขึ้นรหัส Error 50.4 Fuser Malfunction ปิดเปิดใหม่แล้วไม่หาย',
    category: 'Printer',
    priority: 'High',
    status: 'Accepted',
    requesterName: 'คุณนภัสสร รุ่งเรือง',
    requesterPhone: '092-441-2245',
    requesterEmail: 'napassorn.r@univ.ac.th',
    requesterDept: 'กองคลัง อาคารอำนวยการ',
    location: 'กองคลัง อาคารอำนวยการ',
    roomDetails: 'ห้องการเงิน ชั้น 1',
    assetTag: 'PR-FIN-2021-008',
    assetDevice: 'HP LaserJet Enterprise M608',
    impact: 'ไม่สามารถออกเอกสารการจ่ายเช็คได้',
    createdAt: '24 ต.ค. 2024 • 07:45 น.',
    createdAtRelative: 'เมื่อ 1 ชม. ที่แล้ว',
    assignedTech: 'วรวิทย์ ยิ่งยง',
    attachments: [],
    timeline: [],
    comments: [],
  },
  {
    id: 'TK-2024-0875',
    title: 'บัญชีอาจารย์เข้าใช้งานระบบส่งเกรดไม่ได้ แจ้งว่า Password หมดอายุ',
    description: 'อาจารย์เข้าสู่ระบบส่งเกรด Regist SIS ไม่ได้ ระบบแจ้งเตือน Password Expired พยายามรีเซ็ตผ่านอีเมลแล้วไม่ได้รับ OTP',
    category: 'Account',
    priority: 'High',
    status: 'Waiting',
    requesterName: 'นายอนันต์ เกียรติสุข',
    requesterPhone: '086-778-9977',
    requesterEmail: 'anan.k@univ.ac.th',
    requesterDept: 'คณะวิทยาศาสตร์ ภาควิชาเคมี',
    location: 'คณะวิทยาศาสตร์ ภาควิชาเคมี',
    roomDetails: 'ห้องพักอาจารย์ เคมี 3',
    assetTag: 'ID-FAC-CHEM-12',
    assetDevice: 'SSO Portal Account',
    impact: 'กำหนดส่งเกรดสิ้นสุดเวลา 16:30 น. วันนี้',
    createdAt: '24 ต.ค. 2024 • 06:45 น.',
    createdAtRelative: 'เมื่อ 2 ชม. ที่แล้ว',
    attachments: [],
    timeline: [],
    comments: [],
  },
  {
    id: 'TK-2024-0089',
    title: 'จอคอมพิวเตอร์เปิดไม่ติด ไฟไม่เข้า มีกลิ่นไหม้',
    description: 'อาคารวิทย์ 3 ชั้น 4 ห้องปฏิบัติการ 402 เครื่อง Dell Optiplex เปิดสวิตช์แล้วไฟหน้าเคสไม่ติด มีกลิ่นไหม้จางๆ',
    category: 'Computer',
    priority: 'High',
    status: 'Pending',
    requesterName: 'อ.ดร.วิโรจน์ แสงดาว',
    requesterPhone: '081-445-9978',
    requesterEmail: 'wiroj.s@univ.ac.th',
    requesterDept: 'คณะวิทยาศาสตร์ / ภาควิชาเคมี',
    location: 'อาคารวิทย์ 3 ชั้น 4',
    roomDetails: 'ห้องปฏิบัติการ 402 เครื่อง Dell Optiplex',
    assetTag: 'PC-SCI-2020-088',
    assetDevice: 'Dell OptiPlex 5070',
    impact: 'กระทบการทดลองและบันทึกผล',
    createdAt: '24 ต.ค. 2024 • 08:45 น.',
    createdAtRelative: 'เมื่อ 25 นาทีที่แล้ว',
    attachments: [],
    timeline: [],
    comments: [],
  },
  {
    id: 'TK-2024-0088',
    title: 'ระบบ WiFi อาคาร 2 หลุดบ่อยมาก นักศึกษากระทบการสอบ',
    description: 'AP-HU2-Floor3 สัญญาณแกว่ง ไฟส้มกระพริบต่อเนื่อง หลุดทุก 2 นาที นักศึกษาไม่สามารถสอบออนไลน์ได้',
    category: 'Network',
    priority: 'Critical',
    status: 'In Progress',
    requesterName: 'ผศ.นภาพร ใจประสิทธิ์',
    requesterPhone: '089-112-4441',
    requesterEmail: 'napaporn.j@univ.ac.th',
    requesterDept: 'คณะมนุษยศาสตร์ / สนง.คณบดี',
    location: 'อาคาร 2 ชั้น 3',
    roomDetails: 'ห้องสอบคอมพิวเตอร์ 301',
    assetTag: 'AP-HU2-F3-02',
    assetDevice: 'Aruba AP-535',
    impact: 'นักศึกษา 120 คนกระทบการสอบ',
    createdAt: '24 ต.ค. 2024 • 08:12 น.',
    createdAtRelative: 'เมื่อ 1 ชม. ที่แล้ว',
    assignedTech: 'วิศวกรเครือข่าย ปรีชา',
    attachments: [],
    timeline: [],
    comments: [],
  },
  {
    id: 'TK-2024-0087',
    title: 'ขอติดตั้งโปรแกรม AutoCAD 2024 สำหรับเตรียมห้องเรียนปฏิบัติการ',
    description: 'มีลิขสิทธิ์ระดับ Campus License เรียบร้อยแล้ว จำนวน 30 เครื่อง เพื่อเตรียมพร้อมสำหรับสัปดาห์หน้า',
    category: 'Software',
    priority: 'Medium',
    status: 'Accepted',
    requesterName: 'นายชานนท์ วงศ์ศิลป์',
    requesterPhone: '062-889-4499',
    requesterEmail: 'chanon.w@univ.ac.th',
    requesterDept: 'คณะสถาปัตยกรรมศาสตร์ / เจ้าหน้าที่',
    location: 'คณะสถาปัตยกรรมศาสตร์',
    roomDetails: 'ห้องแล็บคอมพิวเตอร์ 102',
    assetTag: 'LAB-ARCH-30',
    assetDevice: 'HP Z2 Workstation 30 เครื่อง',
    impact: 'เตรียมการสอนสัปดาห์หน้า',
    createdAt: '23 ต.ค. 2024 • 16:30 น.',
    createdAtRelative: 'เมื่อวานนี้',
    assignedTech: 'นายสมศักดิ์ ช่างไอที',
    attachments: [],
    timeline: [],
    comments: [],
  },
  {
    id: 'TK-2024-0086',
    title: 'ปริ้นเตอร์กลางกระดาษติดแน่น ดึงไม่ออก และขึ้นเตือน Toner Low',
    description: 'Fuji Xerox DocuPrint P355db ชั้น 2 อาคารอำนวยการ กระดาษติดคาในชุดดรัม และผงหมึกสีดำหมด',
    category: 'Printer',
    priority: 'Medium',
    status: 'Waiting',
    requesterName: 'นางสาวรพีพร พุ่มพวง',
    requesterPhone: '084-556-9912',
    requesterEmail: 'rapeeporn.p@univ.ac.th',
    requesterDept: 'กองบริหารงานบุคคล / แผนกเงินเดือน',
    location: 'อาคารอำนวยการ ชั้น 2',
    roomDetails: 'หน้าแผนกบุคคล',
    assetTag: 'PR-HR-2019-012',
    assetDevice: 'Fuji Xerox DocuPrint P355db',
    impact: 'พิมพ์สลิปเงินเดือนไม่ได้',
    createdAt: '23 ต.ค. 2024 • 14:15 น.',
    createdAtRelative: 'เมื่อวานนี้',
    assignedTech: 'นายสมศักดิ์ ช่างไอที',
    attachments: [],
    timeline: [],
    comments: [],
  },
  {
    id: 'TK-2024-0085',
    title: 'ขอรีเซ็ตรหัสผ่านอีเมลมหาวิทยาลัย (@univ.ac.th) เพื่อส่งเล่มวิทยานิพนธ์',
    description: 'ลืมรหัสผ่านและเบอร์โทรศัพท์ที่ใช้ยืนยัน 2-Factor เปลี่ยนเบอร์ใหม่แล้ว ไม่สามารถล็อกอินเพื่อกดยื่นเล่มจบได้',
    category: 'Account',
    priority: 'Low',
    status: 'Resolved',
    requesterName: 'นายกิตติคุณ มั่งมี (นศ.ปริญญาโท)',
    requesterPhone: '095-778-9966',
    requesterEmail: 'kittikun.m@student.univ.ac.th',
    requesterDept: 'บัณฑิตวิทยาลัย / สาขาบริหารธุรกิจ',
    location: 'ระบบออนไลน์ Graduate Portal',
    roomDetails: 'บริการจากระยะไกล',
    assetTag: 'SSO-STD-650201',
    assetDevice: 'Google Workspace Account',
    impact: 'กำหนดส่งเล่มวิทยานิพนธ์',
    createdAt: '23 ต.ค. 2024 • 11:00 น.',
    createdAtRelative: 'เมื่อวานนี้',
    assignedTech: 'นางสาวกมลวรรณ ดูแลระบบ',
    attachments: [],
    timeline: [],
    comments: [],
  },
  {
    id: 'TK-2024-0084',
    title: 'โปรเจคเตอร์ห้องประชุมสุวรรณภูมิเปิดแล้วดับ มีสัญญาณเตือนหลอดไฟ',
    description: 'มีประชุมสภามหาวิทยาลัยเวลา 13:30 น. ต้องการให้เข้าตรวจสอบด่วน หลอดภาพติดขึ้น 3 วินาทีแล้วตัดดับ ไฟ Temp กระพริบ',
    category: 'Other',
    priority: 'High',
    status: 'Pending',
    requesterName: 'นายนฤดล เชี่ยวชาญ',
    requesterPhone: '083-221-9925',
    requesterEmail: 'narudol.c@univ.ac.th',
    requesterDept: 'กองวิเทศสัมพันธ์และสื่อสารองค์กร',
    location: 'อาคารเฉลิมพระเกียรติ',
    roomDetails: 'ห้องประชุมสุวรรณภูมิ ชั้น 3',
    assetTag: 'PJ-CONF-SWP',
    assetDevice: 'Epson High-Lumen Projector',
    impact: 'การประชุมสภามหาวิทยาลัยบ่ายนี้',
    createdAt: '23 ต.ค. 2024 • 10:05 น.',
    createdAtRelative: 'เมื่อวานนี้',
    attachments: [],
    timeline: [],
    comments: [],
  },
  {
    id: 'TK-2024-0083',
    title: 'สายสัญญาณ LAN หัว RJ-45 เขี้ยวหัก หลุดออกจากเต้ารับผนัง',
    description: 'ห้องพักอาจารย์ ED-308 ต่ออินเทอร์เน็ตผ่านสายไม่ได้ เขี้ยวล็อคสาย LAN หักหลุดจากช่อง Wall plate',
    category: 'Network',
    priority: 'Medium',
    status: 'In Progress',
    requesterName: 'ผศ.ดร.อัจฉรา สุนทร',
    requesterPhone: '086-443-9918',
    requesterEmail: 'atchara.s@univ.ac.th',
    requesterDept: 'คณะศึกษาศาสตร์ / ภาควิชาหลักสูตร',
    location: 'อาคารศึกษาศาสตร์ 3 ชั้น 3',
    roomDetails: 'ห้องพักอาจารย์ ED-308',
    assetTag: 'LAN-PORT-ED-308',
    assetDevice: 'Cat6 Patch Cord 3M',
    impact: 'อัปโหลดงานวิจัยล่าช้า',
    createdAt: '22 ต.ค. 2024 • 15:50 น.',
    createdAtRelative: '2 วันที่แล้ว',
    assignedTech: 'สมชาย ศรีสุวรรณ',
    attachments: [],
    timeline: [],
    comments: [],
  },
  {
    id: 'TK-2024-0082',
    title: 'เบราว์เซอร์เด้งหน้าต่างโฆษณาและเตือนว่าเครื่องติดไวรัส ไม่สามารถปิดได้',
    description: 'เกรงว่าจะกระทบไฟล์เอกสารงบประมาณในเครื่อง ให้ตัดเน็ตและตรวจสอบด่วน มี Pop-up สีแดงเตือนโทรหาหมายเลขปลอม',
    category: 'Software',
    priority: 'Critical',
    status: 'Pending',
    requesterName: 'นางสาวศิริพร สดใส',
    requesterPhone: '087-991-9955',
    requesterEmail: 'siriporn.s@univ.ac.th',
    requesterDept: 'กองคลังและพัสดุ / แผนกจัดซื้อ',
    location: 'กองคลัง อาคารอำนวยการ',
    roomDetails: 'แผนกจัดซื้อ โต๊ะ 04',
    assetTag: 'PC-PRC-2022-004',
    assetDevice: 'Lenovo ThinkCentre M70q',
    impact: 'ความเสี่ยงข้อมูลความลับองค์กร',
    createdAt: '22 ต.ค. 2024 • 13:20 น.',
    createdAtRelative: '2 วันที่แล้ว',
    attachments: [],
    timeline: [],
    comments: [],
  },
  {
    id: 'TK-2024-0081',
    title: 'สอบถามวิธีการตั้งค่า VPN บน macOS Sonoma เพื่อสืบค้นฐานข้อมูลวิจัย',
    description: 'ส่งคู่มือขั้นตอนการติดตั้งและตั้งค่า FortiClient ให้เรียบร้อย อาจารย์ทดสอบเชื่อมต่อจากบ้านสำเร็จ',
    category: 'Account',
    priority: 'Low',
    status: 'Closed',
    requesterName: 'ดร.ธนพล เกษมสัตย์',
    requesterPhone: '082-334-9933',
    requesterEmail: 'thanapol.k@univ.ac.th',
    requesterDept: 'คณะวิศวกรรมศาสตร์ / ภาคเครื่องกล',
    location: 'บริการทางไกล Remote Support',
    roomDetails: 'ออนไลน์',
    assetTag: 'VPN-USER-7712',
    assetDevice: 'MacBook Air M2',
    impact: 'ไม่มีผลกระทบต่อระบบงาน',
    createdAt: '21 ต.ค. 2024 • 09:10 น.',
    createdAtRelative: '3 วันที่แล้ว',
    assignedTech: 'นายสมศักดิ์ ช่างไอที',
    attachments: [],
    timeline: [],
    comments: [],
  },
  {
    id: 'TK-2024-0080',
    title: 'คอมพิวเตอร์สำนักงานมีเสียงแกร๊กๆ จากตัวเคส เปิดติดช้าผิดปกติ',
    description: 'ผู้แจ้งขอยกเลิกเนื่องจากเป็นเครื่องส่วนตัวที่นำเข้ามาใช้เอง และส่งเข้าศูนย์บริการของแบรนด์แล้ว',
    category: 'Computer',
    priority: 'Medium',
    status: 'Cancelled',
    requesterName: 'นายเอกชัย สมบูรณ์ดี',
    requesterPhone: '085-667-9990',
    requesterEmail: 'ekkachai.s@univ.ac.th',
    requesterDept: 'กองแผนงานและพัฒนา',
    location: 'อาคารวิจัยและพัฒนา ชั้น 2',
    roomDetails: 'ห้องแผนงาน โต๊ะ 18',
    assetTag: 'PC-BYOD-091',
    assetDevice: 'Asus VivoPC Personal',
    impact: 'ไม่มีผลกระทบต่อครุภัณฑ์องค์กร',
    createdAt: '20 ต.ค. 2024 • 16:40 น.',
    createdAtRelative: '4 วันที่แล้ว',
    assignedTech: 'สมชาย ศรีสุวรรณ',
    attachments: [],
    timeline: [],
    comments: [],
  },
];

export const INITIAL_ANNOUNCEMENTS = [
  {
    id: 'ann-1',
    tech: 'ช่างวรวิทย์ (IT-04)',
    time: '2 นาทีที่แล้ว',
    text: 'กำลังเปลี่ยนหัวสายสัญญาณ HDMI และทดสอบภาพออกโปรเจกเตอร์ห้อง 201 อาคารเรียนรวม',
    refTicket: 'TK-2024-0888',
    type: 'note',
  },
  {
    id: 'ann-2',
    tech: 'ช่างธนกร (IT-02)',
    time: '18 นาทีที่แล้ว',
    text: 'เปลี่ยนสถานะงานเป็น [แก้ไขเสร็จแล้ว] : แก้ไขการแชร์ไดรฟ์แผนกบุคคลเรียบร้อย',
    refTicket: 'TK-2024-0865',
    type: 'resolved',
  },
  {
    id: 'ann-3',
    tech: 'หัวหน้าศูนย์สารสนเทศ',
    time: '42 นาทีที่แล้ว',
    text: 'มอบหมายงานตรวจสอบอุปกรณ์กระจายสัญญาณ Wi-Fi ชั้น 3 ให้กับ ช่างณัฐพล',
    refTicket: 'TK-2024-0870',
    type: 'assigned',
  },
  {
    id: 'ann-4',
    tech: 'ช่างกิตติศักดิ์ (IT-09)',
    time: '1 ชม. ที่แล้ว',
    text: 'ขอรหัสครุภัณฑ์เพิ่มเติมจากผู้แจ้งซ่อมเครื่องพิมพ์เลเซอร์ คณะบริหารธุรกิจ',
    refTicket: 'TK-2024-0872',
    type: 'waiting',
  },
];
